title: 0x1f440
email: 0x1f440@gmail.com
description: >
  portfolio site by Yura Lee
baseurl: ""
url: "https://0x1f440.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
