title: work in progress
email: 0x1f440@gmail.com
description: >
  work in progress
baseurl: ""
url: "https://0x1f440.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jemoji
  
exclude:
  - Gemfile
  - Gemfile.lock
  
plugins:
  - jemoji